-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: '20f04626a1ee7eb34955d775a37aa9a56a0a7448'
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
        args: ['--django']
