
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7ceee9499e9d00de5548b11c35da3e6074c87fd8",
 "version": "0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
