
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-12T01:21:39-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd0f00d582e39097d7e28d5aadfd05e68836ff77",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
