
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-04T11:17:25+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "bb87b97df22030afbee3236eff27a259b28a9087",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
