language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
os:
- linux
- osx
matrix:
  allow_failures:
    - os: osx
install:
- pip install .
- pip install h5py
- pip install coveralls
- pip install pyorbital
- pip install behave
addons:
  apt_packages:
    - libhdf5-serial-dev
script:
- coverage run --source=satpy setup.py test
- coverage run -a --source=satpy -m behave satpy/tests/features --tags=-download
after_success: coveralls
deploy:
  provider: pypi
  user: Martin.Raspaud
  password:
    secure: RuQzdaLTY4sryIzG8Hz1KWEsyYRxrLvbyfm7DurXDPcj2vsujRwJicNwBrJajIBkzZWwdmWE8db55BPWZwCsJtVUbE53vc742wSAcci2zzCgizSb/jjlDkwk1CE/PoMl4t3JsuIU6bklgw1Y1d4Xn4+BeZe8Blol5PD/FUovxfo=
  on:
    tags: true
    repo: pytroll/satpy
sudo: false
notifications:
  slack:
    rooms:
      - pytroll:96mNSYSI1dBjGyzVXkBT6qFt#satpy
