sudo: false
cache: pip

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - TOXENV=manifest
    - TOXENV=docs

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.3"
          env: TOXENV=py33
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
    exclude:
        - python: "3.3"
          env: TOXENV=docs

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov

notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq

addons:
    code_climate:
        repo_token: e8d763f60ca5495b8bce79682b7c1e2e462a776f8de5c4540ceb01f52458f891


deploy:
    provider: pypi
    user: cthoyt
    password:
        secure: NZSOV7O3swDgUZOX93nXrnvW6O4yRiUUDJQxatPtqNiJS59NQSc11i8uo9zcpLwTmx/6k9VobzcLNLJzMv2u2s7U23fMDURFmhsuGGLZ8qJtcrHyX0QxGRpveZM4RgieWy+RHctQsS6441You+seRowDRr7M3oLOiAylWLJRcAVkG04DyxqWzAL4j+9jrjVM1cKJ8AdvYsc40goYWs3dOddzMUR9f9ik+1aSpZQAjTlCId+mdHhVfDglllnSZWtwBU6RMqknKotQsSC8dmCD87BsUm9m+UP4LMyqjXVqowHZ9BhCPsKAd1ENa6gh69ZvGEgf1qm/qkrTZ9iG3FSQF9WWeqLnvecPf13jl9uZlZGT3NrO8o9nOnRTjpPEsSPFJBPovF3YjoYgNSqjezeAhXs74BKkQaWmvpVorr8zWfSn74pL4+uoDchmwZhw3QGUdfgJZox+pGWDEqtQPfdJTng+H7l6uBWRVCogPwtIRaQqMigMQhGJnpe8BC9KnS7gkOawzA9DZPfUbMPqUTg5RgvHhOYmNtQMvpMQPJYOXe+4028xrJebXBIJVyNGRY+mltCkr4uh8zio+UIOIsmS97zC47xfK06M4nVNvge24EZ0byvbn2qgEHz4gkXz/NjTLi8Uaz9mhHhVMoBxa6u7AQ6DkrT4TEFENShd4yc8qHA=
    on:
        tags: true
        distributions: "sdist bdist_wheel"
        repo: pybel/pybel
        branch: master
