
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-01T23:51:14+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bb11fccfa455fe166f5ef7a5a7e05df99ff8b5b",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
