language: python

sudo: false   # use container-based infrastructure

python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
    apt:
        packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
            - libqt4-dev
            - xvfb

before_cache:   # prevent logs from caching
    - rm -f $HOME/.cache/pip/log/debug.log

cache:
    apt: true
    pip: true
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/pyqt
        - $TRAVIS_BUILD_DIR/orange

before_install:
    - pip install -U pip wheel setuptools
    - pip install codecov

install:
    - source $TRAVIS_BUILD_DIR/.travis/install_pyqt.sh
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install -e .
    # todo: orange cache dir doesn't get created at installation
    - mkdir -p $(python -c 'from Orange.misc.environ import cache_dir; print(cache_dir())')

script:
    - catchsegv xvfb-run coverage run setup.py test

after_success:
    - codecov
