
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-16T14:14:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "024e423246b8578f1db4f56305a6104064204bfc",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
