
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-28T11:53:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e5c50fe810615e483e4e48ceb126f9a688070e4",
 "version": "0.10.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
