
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "32d194ff1b2de48af6c09b2cb85d8fe156d08914",
 "version": "0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
