
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-24T09:46:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b881ee011e1e16dd1a64e197a38e5a09106a8e9",
 "version": "1.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
