
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "93ec53d452ed3bf176f9d285bb29f7991aa9393f",
 "version": "1.0.0.post.dev344"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
