
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-26T17:41:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa5ea1ecb8af29c1aceac9dbbc1206b26a5f0b49",
 "version": "0.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
