
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "10d41d53e4960d9335a9706c2a4b83644d557f07",
 "version": "0.9.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
