
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-23T08:50:21+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "600c403ccbb0d9a25674663775f937d5c03275d8",
 "version": "0.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
