
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.15'
version_full = '8e6c3228ddbf3c687999b01d9911a4aa63805641'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

