
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-02T11:57:45-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e8c8d9e249405cb1a07f3b8fcd90aa1b149b848",
 "version": "0.1a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
