
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-25T12:35:34+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "4ad5942bbb09eff2439755f53eade982148161c4",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
