
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bdf38ed9ca676546332291433fbe3d13010a355f",
 "version": "0.0.0b8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
