
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.8'
version_full = '53bb76af8d2be6f2c7f3bc19d29342d7b23765a3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

