
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-17T14:16:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9989496ff6c47ba60f1973162bd98cbebed8667e",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
