
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c59b3f4f9f95451e121a8eb24a30f5472cd8cf8e",
 "version": "0.0.0b10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
