
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "555ce4488798b5ba4b6742382af17c95f899b692",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
