
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '84682A946524F7F8BE31BC488FFEF20C'
    
_lr_action_items = {'LCODEDELIM':([0,1,2,4,5,6,8,9,10,11,12,15,17,18,20,22,24,27,29,34,41,43,49,69,70,71,72,73,74,],[7,-4,7,-7,-5,-1,-6,-3,-8,16,-2,21,7,-9,-12,7,30,30,-11,-10,-20,-13,-21,-14,-15,-17,-18,-16,-19,]),'INT':([52,53,54,55,],[59,59,59,59,]),'RVARDELIM':([13,],[18,]),'WS':([0,1,2,4,5,6,7,8,9,10,11,12,15,16,17,18,19,20,21,22,24,27,28,29,30,31,32,33,34,38,41,42,43,44,45,46,47,48,49,56,57,58,59,60,61,62,69,70,71,72,73,74,],[1,-4,1,-7,-5,-1,14,-6,-3,-8,1,-2,1,23,1,-9,25,-12,26,1,1,1,35,-11,36,37,39,40,-10,-22,-20,50,-13,51,52,53,54,55,-21,63,64,65,-23,66,67,68,-14,-15,-17,-18,-16,-19,]),'LEN':([31,],[38,]),'ENDIF':([26,36,],[33,33,]),'WORD':([0,1,2,3,4,5,6,8,9,10,11,12,15,17,18,20,22,24,25,27,29,34,41,43,49,69,70,71,72,73,74,],[8,-4,8,13,-7,-5,-1,-6,-3,-8,8,-2,8,8,-9,-12,8,8,31,8,-11,-10,-20,-13,-21,-14,-15,-17,-18,-16,-19,]),'LVARDELIM':([0,1,2,4,5,6,8,9,10,11,12,15,17,18,20,22,24,27,29,34,41,43,49,69,70,71,72,73,74,],[3,-4,3,-7,-5,-1,-6,-3,-8,3,-2,3,3,-9,-12,3,3,3,-11,-10,-20,-13,-21,-14,-15,-17,-18,-16,-19,]),'QUOTEDSTRING':([0,1,2,4,5,6,8,9,10,11,12,15,17,18,20,22,24,27,29,34,41,43,49,50,51,69,70,71,72,73,74,],[4,-4,4,-7,-5,-1,-6,-3,-8,4,-2,4,4,-9,-12,4,4,4,-11,-10,-20,-13,-21,56,57,-14,-15,-17,-18,-16,-19,]),'$end':([1,2,4,5,6,8,9,10,12,18,20,29,34,49,],[-4,0,-7,-5,-1,-6,-3,-8,-2,-9,-12,-11,-10,-21,]),'STRING':([0,1,2,4,5,6,8,9,10,11,12,15,17,18,20,22,24,27,29,34,41,43,49,69,70,71,72,73,74,],[5,-4,5,-7,-5,-1,-6,-3,-8,5,-2,5,5,-9,-12,5,5,5,-11,-10,-20,-13,-21,-14,-15,-17,-18,-16,-19,]),'GT':([39,],[47,]),'EQ':([37,39,],[42,46,]),'RCODEDELIM':([35,37,40,63,64,65,66,67,68,],[41,43,49,69,70,71,72,73,74,]),'NE':([37,39,],[44,48,]),'ELSE':([23,26,],[28,28,]),'IF':([14,23,26,36,],[19,19,19,19,]),'LT':([39,],[45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'block':([0,2,11,15,17,22,24,27,],[9,9,9,9,9,9,9,9,]),'cast_int':([52,53,54,55,],[58,60,61,62,]),'else':([11,15,],[17,22,]),'output':([0,2,11,15,17,22,24,27,],[6,12,6,12,6,6,12,12,]),'word_len':([25,],[32,]),'output_list':([0,11,17,22,],[2,15,24,27,]),'variable':([0,2,11,15,17,22,24,27,],[10,10,10,10,10,10,10,10,]),'if_result':([0,2,11,15,17,22,24,27,],[11,11,11,11,11,11,11,11,]),'end_if':([15,24,27,],[20,29,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> output_list","S'",1,None,None,None),
  ('output_list -> output','output_list',1,'p_output_list_1','parser.py',26),
  ('output_list -> output_list output','output_list',2,'p_output_list_2','parser.py',31),
  ('output -> block','output',1,'p_output','parser.py',36),
  ('output -> WS','output',1,'p_output','parser.py',37),
  ('output -> STRING','output',1,'p_output','parser.py',38),
  ('output -> WORD','output',1,'p_output','parser.py',39),
  ('output -> QUOTEDSTRING','output',1,'p_output','parser.py',40),
  ('output -> variable','output',1,'p_output','parser.py',41),
  ('variable -> LVARDELIM WORD RVARDELIM','variable',3,'p_variable','parser.py',46),
  ('block -> if_result output_list else output_list end_if','block',5,'p_if_else_statement','parser.py',50),
  ('block -> if_result else output_list end_if','block',4,'p_empty_if_else_statement','parser.py',55),
  ('block -> if_result output_list end_if','block',3,'p_if_statement','parser.py',60),
  ('if_result -> LCODEDELIM WS IF WS WORD WS RCODEDELIM','if_result',7,'p_truthy_if','parser.py',65),
  ('if_result -> LCODEDELIM WS IF WS WORD WS EQ WS QUOTEDSTRING WS RCODEDELIM','if_result',11,'p_equality_if','parser.py',70),
  ('if_result -> LCODEDELIM WS IF WS WORD WS NE WS QUOTEDSTRING WS RCODEDELIM','if_result',11,'p_non_equality_if','parser.py',76),
  ('if_result -> LCODEDELIM WS IF WS word_len WS GT WS cast_int WS RCODEDELIM','if_result',11,'p_len_gt_if','parser.py',82),
  ('if_result -> LCODEDELIM WS IF WS word_len WS LT WS cast_int WS RCODEDELIM','if_result',11,'p_len_lt_if','parser.py',87),
  ('if_result -> LCODEDELIM WS IF WS word_len WS EQ WS cast_int WS RCODEDELIM','if_result',11,'p_len_equality_if','parser.py',92),
  ('if_result -> LCODEDELIM WS IF WS word_len WS NE WS cast_int WS RCODEDELIM','if_result',11,'p_len_non_equality_if','parser.py',97),
  ('else -> LCODEDELIM WS ELSE WS RCODEDELIM','else',5,'p_else','parser.py',102),
  ('end_if -> LCODEDELIM WS ENDIF WS RCODEDELIM','end_if',5,'p_end_if','parser.py',107),
  ('word_len -> WORD LEN','word_len',2,'p_word_len','parser.py',112),
  ('cast_int -> INT','cast_int',1,'p_cast_int','parser.py',116),
]
