
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-21T12:49:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "582173ed9838a9b55a7496caf83a65ed6055287e",
 "version": "2017.3.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
