---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "heat-api"
    - "heat-api-cfn"
    - "heat-engine"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "heat-api"
    - "heat-api-cfn"
    - "heat-engine"

- name: Copying over the heat-engine environment file
  template:
    src: "_deprecated.yaml"
    dest: "{{ node_config_directory }}/{{ item }}/_deprecated.yaml"
  with_items:
    - "heat-engine"

- name: Copying over heat.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/heat.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/heat.conf"
      - "{{ node_custom_config }}/heat/{{ item }}.conf"
      - "{{ node_custom_config }}/heat/{{ inventory_hostname }}/heat.conf"
    dest: "{{ node_config_directory }}/{{ item }}/heat.conf"
  with_items:
    - "heat-api"
    - "heat-api-cfn"
    - "heat-engine"
