
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-27T20:41:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "29f127e8de57cfff7e28359345ce0e5f9e99cc25",
 "version": "0.47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
