
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-14T05:29:52+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "d6db9efec62022fb366d87936b1a17f961112336",
 "version": "0.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
