
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-06T16:07:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c0e18a3d4c8236c4c0622775d0487e1f40973f6",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
