
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.1.5'
version_full = '85ca5b02fd009471a7b6dd35537aa74569aaa4da'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

