language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

install:
  - pip install -r test-requirements.txt

script:
  - nosetests --with-doctest --doctest-options=+ELLIPSIS tests.py autorepr.py
