
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.4'
version_full = 'fefadfddbebad10a87c5796e385575e757542ade'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

