
'''
This file is automatically generated by setup.py, So don't edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.10.3',
    'branch_nick': '(detached',
    'revision_id': 'b3e76f79dda668d55d648e22051d0efcd21ce07f',
    'revno': 4857
}
