
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "35774502357b99f688e93b6ef835fe96d5810e12",
 "version": "1.2.151"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
