
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-01T16:32:05-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0b99026757dbd2a2d25128993ce79734d17590d",
 "version": "0.1.0-rc.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
