
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.7'
version_full = 'f7750767a55261cd726ea32c7b8224c9461bd457'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

