
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-02T13:06:44+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "1023ea9dfea85efa35775336386818e6926b167c",
 "version": "1.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
