# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_devicemanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac',
            new_name='MAC',
        ),
    ]
