# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_devicemanager', '0002_auto_20170213_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Default', max_length=64),
            preserve_default=False,
        ),
    ]
