
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-28T16:30:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f87e4cca4291ebefc3999bb06cb2d8f31948415",
 "version": "0.47.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
