__version__ = "0.6.30"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'git@git.infinidat.com:host-opensource/infi.instruct.git'
__git_head_hash__ = '3284a493e00be587164919b585ef5a45aa1ea613'
__git_head_subject__ = u'Finished Release v0.6.30'
__git_head_message__ = u'* develop:\n  HOSTDEV-2654 reverting the endianess fix until we come up with a better one'
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-03-05 14:00:06'
