
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-14T14:14:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6560b7287bffae83c51c05b451b9c7b8ab56d23",
 "version": "v0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
