
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-03T13:19:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cace2b69fe1fdd8a2c5e4437fffa49e1d1d34af4",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
