
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e5fa73c5af5c9b2913adaef6b2b03ba5e389da62",
 "version": "0.post.dev412"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
