# -*- coding: utf-8 -*-
# Copyright (c) 2015, pyretis Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for pyretis.

This file is generated by pyretis (``setup_version.py``)
"""
SHORT_VERSION = '0.2.1.dev0'
VERSION = '0.2.1.dev0'
FULL_VERSION = '0.2.1.dev0'
GIT_REVISION = 'e3a444fddf000a6395e30881b93ee812abae099e'
GIT_VERSION = '0.2.1.dev0+e3a444f'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
