# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-09-25 03:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0004_auto_20150921_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='The attributes of the boundary from the shapefile, as a dictionary.'),
        ),
        migrations.AlterField(
            model_name='boundaryset',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='Any additional metadata.'),
        ),
    ]
