
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-22T11:11:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac75d29c15fdddf934a654e0b2705d237913a33c",
 "version": "1.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
