__version__ = "0.3.14"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.3.14)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '747ec8f9208bd4dbf44f40eba6f90f2710d56dcd'
__git_head_subject__ = u'Finished Release v0.3.14'
__git_head_message__ = u''
__git_dirty_diff__ = u''