
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0138e375da4353a01f381a26a9135a3a5fcc443d",
 "version": "2.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
