
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f6d686e7dd4b79eea68421ce16ac86a34bc1e92c",
 "version": "0.0.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
