
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-01-17T12:37:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e4ef5ef534f68c6de9982c04d475e27140835b9",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
