sudo: false
language: python
cache: pip

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

env:
  matrix:
    - BUILD=py
    - BUILD=flake8
    - BUILD=docs
  global:
    secure: IFQzIw/g6qbmZy86w9qPU5vZjoJWtBlP8VpUtBX+La9hyZ6odC0pxB38U7IQNnPKinUvnc0cGEsAJS/abxp3bSdS0H+afr8OjxOgDuLBl47fMHBxFUMF6HRFmKuk66GfM1sxf87xLdiPDF5Dac0cn7IlJrFkQaCukZjinvZRvtU=

matrix:
  allow_failures:
    - python: 3.7-dev
  exclude:
    # Sphinx requires python 3.4 or above
    - python: 3.3
      env: BUILD=docs

addons:
  apt:
    packages:
      - language-pack-de

install:
  - pip install tox codecov

script:
  - tox -e $BUILD

after_script:
  - codecov

deploy:
  provider: pypi
  user: hobarrera
  password:
    secure: LXSgJZMZICS0Xv5qyR/IRgki1Wy23lurmdepsOsjzBM2fv7rgKPlU/MASVCUCmLi9vYYqZu+7ViHeT6uhJXLdwE0NisVYqTg6L4aD1kqDmbjkWFhLKA7DAz1QTAYxrk6TQYmDb+ZbNFZlF21g29nqvqtLwdC4dFnDjXGnupCoeU=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
