
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4e2c8923e759c5984ffd014be2ec2484bbf69795",
 "version": "0.0.0b7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
