---
- name: Pulling sahara-engine image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ sahara_engine_image_full }}"
  when: inventory_hostname in groups['sahara-engine']

- name: Pulling sahara-api image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ sahara_api_image_full }}"
  when: inventory_hostname in groups['sahara-api']
