__version__ = "0.4.18"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'git@git.infinidat.com:host-opensource/infi.storagemodel.git'
__git_head_hash__ = 'f5b9e26b68725aca77aa3e090f4c104150b9abf5'
__git_head_subject__ = u'Finished Release v0.4.18'
__git_head_message__ = u'* develop:\n  HPTVM-1155 ignore hardware iscsi adapters'
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-03-09 12:00:00'
