
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-27T09:33:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa8f29885daba0c0bfeae494ddbf4d319703ba00",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
