
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "43478223748a3a7572f64687987ab6d9abe2c44c",
 "version": "1.0.0.post.dev340"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
