
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "27ea21ea6463162b327932fd7f7245ce452d069c",
 "version": "1.2.152"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
