
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-01T11:32:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a4807e28313fcf7401931c5ced3f24b76dd57f1",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
