
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "114702646c5e6d6325989583c6e626a5ba951605",
 "version": "0.0.0b11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
