
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-24T12:18:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "269815d85f4c78b95ccaa907dab9ad04f5034049",
 "version": "1.0.0a17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
