
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3d33cb370a75ff7d430047c72b35af5ef7dae302",
 "version": "0.0.0a32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
