# coding: utf-8
# Generated by setup.py for PyCBC on 2017-02-20 19:58:33 +0000.

version = '1.6.7'
date = '2017-02-20 19:48:29 +0000'
release = True
last_release = '1.6.7'

git_hash = 'b278146f5f0859c932e18f94a78411bc7460d2b9'
git_branch = 'None'
git_tag = 'v1.6.7'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Duncan Brown <duncan.brown@ligo.org>'
git_build_date = '2017-02-20 19:58:33 +0000'
git_verbose_msg = """Branch: None
Tag: v1.6.7
Id: b278146f5f0859c932e18f94a78411bc7460d2b9
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2017-02-20 19:58:33 +0000
Repository status is CLEAN: All modifications committed"""