---
keystore_path: "/home/herlo/Projects/virtualenvs/lp090/lib/python2.7/site-packages/keystore"
outputfolder_path: "/home/herlo/Projects/virtualenvs/lp090/lib/python2.7/site-packages/outputs "
inventoryfolder_path: "/home/herlo/Projects/virtualenvs/lp090/lib/python2.7/site-packages/inventory"
async: False
async_timeout : 1000
no_output : False
schema: "/home/herlo/Projects/virtualenvs/lp090/lib/python2.7/site-packages/ex_schemas/schema_v3.json"
inventory_layouts_path: "/home/herlo/Projects/virtualenvs/lp090/lib/python2.7/site-packages/inventory_layouts"
inventory_outputs_path: "/home/herlo/Projects/virtualenvs/lp090/lib/python2.7/site-packages/inventories"
check_mode: "no"