---
- include: do_reconfigure.yml
  when: inventory_hostname in groups['gnocchi-api']
        or inventory_hostname in groups['gnocchi-metricd']
        or inventory_hostname in groups['gnocchi-statsd']
