
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-15T17:42:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "072683b0b6f3d2d0952b0b19ab6ff96f15dc9ce6",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
