
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "aee19c64ad1534f0ee14a99cf1081764ffbef579",
 "version": "v0.0.0.post149.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
