---
- name: Starting tempest container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ tempest_image_full }}"
    name: "tempest"
    volumes:
      - "{{ node_config_directory }}/tempest/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
