sudo: false
language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
# disabled per https://github.com/cherrypy/cheroot/issues/21
# - pypy
- pypy3
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - env: TOXENV=pre-commit-pep257
  include:
  - python: 3.6
    env: TOXENV=pre-commit
  - python: 3.6
    env: TOXENV=pre-commit-pep257
cache:
  pip: true
  directories:
  - $HOME/.pre-commit
before_install:
- "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then . .travis/replace-pypy3 ; fi"
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: RAfz06AINvz7bfij/YhfkAreRqamgxS8a6jSRNxntYhtJke3ZszUbIDag8+n1I+G5XT2LnMhHqPNR7Plc+AeMz7VXTuy+b81Li5kse20NYlPhd7mBVmTUpXtqYQashV5J39F4qkATBLznCOrMEomM07VTXjO/o2hmQuXniab2Uo=
