
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "667cd7ba3c05cc4deeae4fd74df0de84f542600e",
 "version": "1.2.137"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
