
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "358aef3bb2d0155737b72c21d85f2c774afbef8b",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
