
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-17T19:15:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "de2ef1830da13f4eaf7e48f41150ed9ba57095f0",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
