motioneye:
  image: motioneye
  volumes:
    - /mnt/motioneye/media:/media
    - /mnt/motioneye/config:/etc/motioneye
  environment:
    - "TZ=Pacific/Auckland" # See http://php.net/manual/en/timezones.php
  ports:
    - 8081:8081
    - 8765:8765
  restart: always
