
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-26T21:30:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9e498aee3fb2ff2acc3b1a4a92f5e18ccf4a825",
 "version": "2017.3.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
