# This file was auto-generated by salt's setup on Friday, 24 March 2017 @ 18:03:02 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2016, 3, 6, 0, 0, 0, None)
