
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d33985f0486108f2fca34c75410ac0762569ecae",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
