
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-21T13:45:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "68caf5492394a078ee22a743a97d68052b3ba0c8",
 "version": "4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
