
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-09T01:02:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccd4772f8a6987e63d4eb99fde7bb9c4866e68cc",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
