language: python
python: '3.5'
sudo: false
env:
  - TOXENV=check
  - TOXENV=py27,codecov
  - TOXENV=py34,codecov
  - TOXENV=py35,codecov
  - TOXENV=pypy,codecov

matrix:
  fast_finish: true
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - pip install codecov
install:
  - pip install tox
  - pip install -r requirements/ci.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - git clone https://github.com/Pawamoy/keycut-data keycut_data
  - export KEYCUT_DATA="${PWD}/keycut_data/default"
branches:
  only:
    - master
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - codecov
