
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "37cf09eb245d26a681c6c1d3a9c817390dbca30b",
 "version": "0.0.0a35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
