
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "519f97d44a5ea6cbcaafc6c5659eabaa769245a3",
 "version": "0.0.0a28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
