
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "73364a54088a675ca77ad820c2705af5da738c28",
 "version": "2.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
