
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-02T23:45:51+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "56ad5f29e48bd155a4b1b6e46e5824296fb5ae05",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
