
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-14T17:11:56-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed34bf0573926a7c9b21303948fd6f98a067cb58",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
