
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-17T17:50:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd080f09fce965168dfb65a4ba110039a22c4e86",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
