# ============================================================================
# Config file for Denovo Assembly
#
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_extension: "%(input_extension)s"
input_pattern: "%(input_pattern)s"
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# =========================================== Sequencing information

sequencing:
    platform: "Illumina"
    instrument: "Hiseq2500"
    flowcell: "Unknown"

# Do you want to do mapping evaluation of your assembly ?
do_mapping_evaluation: yes

# =========================================== Sections related to assembly tools

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Digital normalization

digital_normalisation:
    do: yes
    # kmer size to use
    ksize: 20
    # when median k-mer coverage level is above the number the read is not kept
    cutoff: 20
    # number of tables and size of tables. 
    # memory used is i(n_table * max-tablesize) bytes.
    n_tables: 4
    max-tablesize: 3e9
    threads: 4
    options: ""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Spades

spades:
    threads: 8
    options: '--careful'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Quast

quast:
    options: ''

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Format contigs

format_contigs:
    length_min: 500

# =========================================== Sections related to mapping evaluation

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Bwa

bwa_mem_ref:
    # IS is for small genome and bwtsw for large genome (like human)
    index_algorithm: 'is' # Algorithm for constructing index [is|bwtsw]
    options: '-T 30'
    threads: 2

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Freebayes

freebayes:
    ploidy: 1  # Set the ploidy of your sample (default:2)
    options: ''

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Indel realigner (GATK)

indel_realigner:
    do: yes

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Mark duplicates (picard-tools)

mark_duplicates:
    do: yes
    option: ""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Bam quality filter

bam_quality_filter:
    do: yes
    threshold: 30  # Minimum MAPQ score allowed

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Report Mapping

report_mapping:
    do: yes
    k: 1                      # Number of gaussian predicted
    circular: no              # If your genome is circular
    window_size: 5001        # Window size for compute the running median
    high_threshold: 4.0       # Threshold to detect high coverage regions 
    low_threshold: -4.0       # Threshold to detect low coverage regions

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ VCF filter (dedicated to freebayes)

vcf_filter:
    freebayes_score: 100         # Minimal freebayes score
    frequency: 0.8               # Minimal alternative allele frequency
    min_depth: 10                    # Minimal coverage depth
    forward_depth: 3             # Minimal coverage depth of forward strand
    reverse_depth: 3             # Minimal coverage depth of reverse strand
    strand_ratio: 0.2            # Minimal strand ratio between 0 and 0.5 
