
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-17T09:22:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ee44a6db9fd98713da1a0829a886c4417101d5b",
 "version": "1.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
