
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4c826a5e8aec310511cabe609c0aba0459a4c399",
 "version": "0.13.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
