language: python
python: '3.5'
sudo: false
env:

  - TOXENV=check


  - TOXENV=py27-django-18,codecov
  - TOXENV=py27-django-19,codecov
  - TOXENV=py27-django-110,codecov


  - TOXENV=py34-django-18,codecov
  - TOXENV=py34-django-19,codecov
  - TOXENV=py34-django-110,codecov


  - TOXENV=py35-django-18,codecov
  - TOXENV=py35-django-19,codecov
  - TOXENV=py35-django-110,codecov


  - TOXENV=py36-django-18,codecov
  - TOXENV=py36-django-19,codecov
  - TOXENV=py36-django-110,codecov


  - TOXENV=pypy-django-18,codecov
  - TOXENV=pypy-django-19,codecov
  - TOXENV=pypy-django-110,codecov

matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py27-django-18,codecov
    - env: TOXENV=py34-django-18,codecov
    - env: TOXENV=py35-django-18,codecov
    - env: TOXENV=py36-django-18,codecov
    - env: TOXENV=pypy-django-18,codecov

before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - pip install codecov
  - pip install django
install:
  - pip install tox
  - pip install -r requirements/ci.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
branches:
  only:
    - master
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - codecov
  
