
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-21T05:50:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e99836ba3bb4538ab4843b8fc6df387bbbdaffce",
 "version": "1.0.0a16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
