
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-23T16:27:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e7932f8b86e6d03bf9fdadeb2a68a4ee171e58f",
 "version": "0.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
