# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joda_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joda_core.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('joda_core.document',),
        ),
        migrations.CreateModel(
            name='MiscType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='miscdocument',
            name='misc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joda_misc.MiscType'),
        ),
    ]
