
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-22T13:30:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "565b67a519d31db0bfd1cb12c8905bca8dcf8f0a",
 "version": "2017.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
