
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2ddd2e36a3fb68cd55d45f205b2a0850a1368307",
 "version": "1.2.145"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
