
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d2aa9e923c59a85bb709bf9fd45c4e5c3f8762ce",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
