
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-18T00:14:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d53a2b59ea1af4290f0bb23ee2fb5c226662157e",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
