
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-26T13:56:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b41cce155b88d90c3ea2da18054f4015ea1858c",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
