
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "992270aa29b53e20a8be442064b784c8c12378f4",
 "version": "0.0.0a27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
