version: '2'
services:
  novaideo:
    build:
      context: .
      args:
        run_buildout: "false"
    stdin_open: true
    tty: true
    environment:
      - SECRET=mybigsecret
      - APPLICATION_URL=http://local.ecreall.com:8080
      - MAIL_DEFAULT_SENDER=contact@example.com
      - TIMEOUT=999999999
      - MAILER_HOST=172.17.0.1
      - MAILER_PORT=9025
    ports:
     - "5000:5000"
    volumes:
      - ./var:/app/var
      - ./cache:/app/cache
      - ./etc/varnish.vcl:/app/etc/varnish.vcl:ro
      - ./novaideo:/app/novaideo
  nginx:
    image: undownding/nginx-http2
    volumes:
      - ./nginx-app-dev.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/etc/nginx/html:ro
      - ./tls:/etc/nginx/tls:ro
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - novaideo:app
