
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-06T16:51:42+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "55b1c3a3507c8b8ab28f18aad68f6210083cc107",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
