# coding: utf-8
import struct

#region メッセージID
MSG_REQ_START_COMM = 0x00
MSG_ACK_START_COMM = 0x10
MSG_NOTIFY_END_COMM = 0x01
MSG_NOTIFY_CONTROL_COMMAND = 0x02
MSG_SEND_SPEECH_DATA = 0x03
MSG_NOTIFY_STOP_COMM = 0x11
MSG_ACK_SEND_SPEECH_DATA = 0x12
MSG_NOTIFY_COMPLETE_SPEECH = 0x13
MSG_REQ_CANCEL_SPEECH = 0x04
MSG_ACK_CANCEL_SPEECH = 0x14
MSG_SEND_SPEECH_RECOGNITION_COMMAND = 0x15
MSG_ACK_SEND_SPEECH_RECOGNITION_COMMAND = 0x05
MSG_CLIENT_OFFLINE = 0x99
MSG_CLIENT_NONE_MESSAGE = 0xaa
MSG_SEND_SPEECH_DATA_AUTO = 0x50   #Debug用
#endregion

#region 変数・定数定義
RECEIVE_POLLING_TIME_OUT = 2        #2sec
RECEIVE_TIME_OUT = 40               #40sec
RECEIVE_MAX_TIME_OUT = 60           #60sec
RECEIVE_MIN_TIME_OUT = 10           #10sec
WRITE_TIME_OUT = 10                 #10sec
SEND_TIME_OUT = 10                  #10sec
THREAD_JOIN_TIME_OUT = 5            #5sec
SEND_READ_DATA_MAX_SIZE = 1024
#@SEND_READ_DATA_MAX_SIZE = 12
RECEIVE_RETRY_MAX_COUNT = 3
HRSEULT_SOCKET_CLOSED = -2147483629

#共通エラーメッセージ
HZ_ERROR_RECEIVE_TIMEOUT = 0x01;              #応答受信タイムアウト
HZ_ERROR_OTHER_REASON = 0x99;                 #その他理由
#endregion






