
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "eb6a7f9b0ee4d663eebb396d0e8da5a63a5aebc1",
 "version": "v0.0.0.post151"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
