
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-20T14:20:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0dc7117f4c3523ef60d967d42c2afc5e2ba3adc0",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
