
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-10T10:31:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "330ef0b1480b0a38e8334ae01364194036a4f06d",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
