sudo: required
dist: trusty
language: python
python:
- '2.7'
- '3.5'
before_install: 
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: biocommons
  password:
    secure: KORDD+pZEYuSxl4l6oG3PWjtM3SHnnuazz0Xb7lO36sx4xq2xYiOlObftpZvrt1VMIjpg/nn1UVYwjMung+ALfdHTWnwiij4o7KrUVfIq2qNa3Tgy3/wH9DVn3YdZFXgArN2MhVTy0gibb+hvnZQwHPfBPXwayuzP7x3kaledtAhLwmuy68V3qGOsfpp9fdb11scFOJjWWTM2SJHxbmMbwKX36GlGA3+wFF78s/PQ2nxg5oV9ZuN1bFXxyvZVu/yiAONgYauDZbl4CscUBOVOkDczYZ8xv8ehrdoPykru8R7J8kgT9qImiwPWidDQCKqjTwhr9QGS6CvO/5qiFSAU3Gq2SG/LySPebCxjuYeTd8SpSwNDDWOvQ9YhzdHyMC0jwDxwdCbXGvi6PnpvlnrSNiTGhu1kfUZ5GcQUrW6QjVlAtPrqrEEyTkAjyD9oyOL/UyRxVyDr4QFvGSYnnNRz67S4VkxRD9za6yWI2aePSttg1v6EZVBwcZZH+LjinTbzPmEnXM4TglILmRLVdt5/xPp0fBQpm5CWEQFxuoHy3LYq9UXrKh1qE+53P7wmMKnBjCmoRcBO2sfQdzavOER/NObimiu2IQTRywntANBl5Ox6ELlmrwklDThbTDW9k5zu+eZUjHddVetkFrYyj35VqJ+h3sSQDNPFSN7iVSsFxU=
  on:
    tags: true
    distributions: "sdist bdist_wheel"
    branch: master
