# App settings go here, they're validated in app.main.load_settings
dev:
  py_file: app/main.py
  static_path: static/
# {% if database.is_none and example.is_message_board %}
message_file: 'messages.txt'
# {% elif database.is_pg_sqlalchemy %}
database:
  name: '{{ clean_name }}'
  user: 'postgres'  # TODO you need to make sure connection settings here are correct
  # you can override password without saving it with an env variable: `APP_DATABASE_PASSWORD=waffle`
  password: 'You need to set this!'
  host: localhost
  port: 5432
# {% endif %}
# {% if session.is_secure %}
# this is the key used to encrypt cookies. Keep it safe!
# you can generate a new key with `base64.urlsafe_b64encode(os.urandom(32))`
cookie_secret_key: '{{ cookie_secret_key }}'
# {% endif %}
