
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-11T12:33:35-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "96b8754b9a437814b1868b4de75bdddc3f8eb246",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
