
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-19T20:36:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "eac2e1e02ae53cd64869ea7e3d953f5e487a2e8a",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
