
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9bbb08afc6a3023765a21ff011c7cd77f73d511c",
 "version": "1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
