
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.10.1',
    'branch_nick': '(detached',
    'revision_id': '80414fb5a15f6aca75ce1e346a7991eceaac6498',
    'revno': 4777
}
