
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-20T15:56:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d2b56715c64a537eb4a9a814c4804cbd8bef084",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
