
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-24T15:43:20+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "cffc5c2f4fb17d6f3c7d558ed0ef0edd80e4c8b9",
 "version": "0.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
