
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-16T07:42:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "199fe6df71f3fa53a4093a259dbe62732a1a3848",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
