---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "ceilometer-notification"
    - "ceilometer-collector"
    - "ceilometer-api"
    - "ceilometer-central"
    - "ceilometer-compute"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "ceilometer-notification"
    - "ceilometer-collector"
    - "ceilometer-api"
    - "ceilometer-central"
    - "ceilometer-compute"

- name: Copying over ceilometer-api.conf
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/ceilometer-api/wsgi-ceilometer-api.conf"
  with_first_found:
    - "{{ node_custom_config }}/ceilometer/{{ inventory_hostname }}/wsgi-ceilometer-api.conf"
    - "{{ node_custom_config }}/ceilometer/wsgi-ceilometer-api.conf"
    - "wsgi-ceilometer-api.conf.j2"

- name: Copying over ceilometer.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/ceilometer.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/glance.conf"
      - "{{ node_custom_config }}/glance/{{ item }}.conf"
      - "{{ node_custom_config }}/ceilometer/{{ item }}.conf"
      - "{{ node_custom_config }}/ceilometer/{{ inventory_hostname }}/ceilometer.conf"
    dest: "{{ node_config_directory }}/{{ item }}/ceilometer.conf"
  with_items:
    - "ceilometer-notification"
    - "ceilometer-collector"
    - "ceilometer-api"
    - "ceilometer-central"
    - "ceilometer-compute"

- name: Copying over event and pipeline yaml for notification service
  template:
    src: "{{ item }}.j2"
    dest: "{{ node_config_directory }}/ceilometer-notification/{{ item }}"
  with_items:
    - "event_definitions.yaml"
    - "event_pipeline.yaml"
    - "pipeline.yaml"
