
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-02T15:36:26+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "64dc14fc4bac3896d73264f692277f761e1e2ac4",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
