# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_reviews', '0003_auto_20170223_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pcart_customers.Customer', verbose_name='Customer'),
        ),
    ]
