
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-23T20:18:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4ad43e0905590eea68aa8a3b17b70a7742a1c36",
 "version": "0.0.1-alpha.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
