# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tinycom/tinycom.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from .qt import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(759, 679)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/32x32/tinycom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.echo_input = QtGui.QCheckBox(self.centralwidget)
        self.echo_input.setObjectName(_fromUtf8("echo_input"))
        self.gridLayout.addWidget(self.echo_input, 1, 1, 1, 1)
        self.btn_open = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open.sizePolicy().hasHeightForWidth())
        self.btn_open.setSizePolicy(sizePolicy)
        self.btn_open.setObjectName(_fromUtf8("btn_open"))
        self.gridLayout.addWidget(self.btn_open, 0, 0, 1, 1)
        self.remove_escape = QtGui.QCheckBox(self.centralwidget)
        self.remove_escape.setObjectName(_fromUtf8("remove_escape"))
        self.gridLayout.addWidget(self.remove_escape, 1, 0, 1, 1)
        self.serial_str = QtGui.QLabel(self.centralwidget)
        self.serial_str.setObjectName(_fromUtf8("serial_str"))
        self.gridLayout.addWidget(self.serial_str, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.log = QtGui.QPlainTextEdit(self.frame)
        self.log.setAcceptDrops(False)
        self.log.setReadOnly(True)
        self.log.setObjectName(_fromUtf8("log"))
        self.gridLayout_3.addWidget(self.log, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_clear = QtGui.QPushButton(self.frame)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.horizontalLayout_3.addWidget(self.btn_clear)
        self.output_hex = QtGui.QCheckBox(self.frame)
        self.output_hex.setObjectName(_fromUtf8("output_hex"))
        self.horizontalLayout_3.addWidget(self.output_hex)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.enable_log = QtGui.QCheckBox(self.frame)
        self.enable_log.setText(_fromUtf8(""))
        self.enable_log.setObjectName(_fromUtf8("enable_log"))
        self.horizontalLayout_2.addWidget(self.enable_log)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.log_file = QtGui.QLineEdit(self.frame)
        self.log_file.setObjectName(_fromUtf8("log_file"))
        self.horizontalLayout_2.addWidget(self.log_file)
        self.btn_open_log = QtGui.QPushButton(self.frame)
        self.btn_open_log.setObjectName(_fromUtf8("btn_open_log"))
        self.horizontalLayout_2.addWidget(self.btn_open_log)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.history = QtGui.QListWidget(self.frame_2)
        self.history.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.history.setObjectName(_fromUtf8("history"))
        self.gridLayout_2.addWidget(self.history, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.input = QtGui.QLineEdit(self.centralwidget)
        self.input.setToolTip(_fromUtf8(""))
        self.input.setObjectName(_fromUtf8("input"))
        self.horizontalLayout.addWidget(self.input)
        self.line_end = QtGui.QComboBox(self.centralwidget)
        self.line_end.setObjectName(_fromUtf8("line_end"))
        self.line_end.addItem(_fromUtf8(""))
        self.line_end.addItem(_fromUtf8(""))
        self.line_end.addItem(_fromUtf8(""))
        self.line_end.addItem(_fromUtf8(""))
        self.line_end.addItem(_fromUtf8(""))
        self.line_end.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.line_end)
        self.btn_send = QtGui.QPushButton(self.centralwidget)
        self.btn_send.setObjectName(_fromUtf8("btn_send"))
        self.horizontalLayout.addWidget(self.btn_send)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuAbout.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TinyCom", None))
        self.echo_input.setToolTip(_translate("MainWindow", "Put any input in the output window automatically.", None))
        self.echo_input.setText(_translate("MainWindow", "Local Echo", None))
        self.btn_open.setText(_translate("MainWindow", "&Open Device", None))
        self.remove_escape.setToolTip(_translate("MainWindow", "Remove ANSI escape sequences in the output and log.", None))
        self.remove_escape.setText(_translate("MainWindow", "Remove ANSI Escape Sequences", None))
        self.serial_str.setText(_translate("MainWindow", "Not connected", None))
        self.log.setToolTip(_translate("MainWindow", "Output log.", None))
        self.btn_clear.setToolTip(_translate("MainWindow", "Clear output log window.", None))
        self.btn_clear.setText(_translate("MainWindow", "C&lear", None))
        self.output_hex.setText(_translate("MainWindow", "Hex Output", None))
        self.enable_log.setToolTip(_translate("MainWindow", "Enable logging to file.", None))
        self.label_7.setText(_translate("MainWindow", "Log To:", None))
        self.log_file.setToolTip(_translate("MainWindow", "Log file path.", None))
        self.log_file.setText(_translate("MainWindow", "tinycom.log", None))
        self.btn_open_log.setToolTip(_translate("MainWindow", "Select log file.", None))
        self.btn_open_log.setText(_translate("MainWindow", "...", None))
        self.history.setToolTip(_translate("MainWindow", "Input history", None))
        self.label_3.setText(_translate("MainWindow", "Input:", None))
        self.line_end.setToolTip(_translate("MainWindow", "Select line ending type to append.", None))
        self.line_end.setItemText(0, _translate("MainWindow", "LF line end", None))
        self.line_end.setItemText(1, _translate("MainWindow", "CR line end", None))
        self.line_end.setItemText(2, _translate("MainWindow", "CR/LF line end", None))
        self.line_end.setItemText(3, _translate("MainWindow", "LF/CR line end", None))
        self.line_end.setItemText(4, _translate("MainWindow", "No line end", None))
        self.line_end.setItemText(5, _translate("MainWindow", "Hex", None))
        self.btn_send.setToolTip(_translate("MainWindow", "Send the input.", None))
        self.btn_send.setText(_translate("MainWindow", "&Send", None))
        self.menuAbout.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from . import tinycom_rc
