
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-25T09:00:16+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "ad9a7bd802b2889e2b056fdab867222138d44817",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
