
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2fe071691b8533d7f7a86dd9f8c547f1c2076f08",
 "version": "0.0.0b12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
