
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-17T22:20:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73a189c4561859c6617b6194faf869ec0cd2a6b3",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
