
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cba2056722ae529170177d40f3745d4329a49fc9",
 "version": "1.2.128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
