
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f9a4e360606b9070da343868646ebdc4d146b562",
 "version": "0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
