language: python
sudo: false
notifications:
  email: false
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install pytest pytest-cov

script:
  - python setup.py test
after_success:
  # report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
