
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "716866d63ce63ce82fe269e9fb9069e640b7720d",
 "version": "1.0.0.post.dev305"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
