
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-14T15:57:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3f715660c8b62de4092dcc7feddd4a930b9c1b9",
 "version": "1.2.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
