
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-24T18:25:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "758edc6ec91caf04712a6ba9c4a8eeac095e3f3a",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
