language: python


# these combos of python and numpy are not supported by
# anaconda:
# python 2.6* numpy 1.11*
# python 3.3* numpy 1.11*
# python 3.5* numpy 1.8*

# Here is a matrix that anaconda supports:
env:
    - PYTHON_VERSION=2.6 NUMPY_VERSION=1.8
    - PYTHON_VERSION=2.6 NUMPY_VERSION=1.9

    - PYTHON_VERSION=2.7 NUMPY_VERSION=1.8
    - PYTHON_VERSION=2.7 NUMPY_VERSION=1.9
    - PYTHON_VERSION=2.7 NUMPY_VERSION=1.11

    - PYTHON_VERSION=3.3 NUMPY_VERSION=1.8
    - PYTHON_VERSION=3.3 NUMPY_VERSION=1.9

    - PYTHON_VERSION=3.4 NUMPY_VERSION=1.8
    - PYTHON_VERSION=3.4 NUMPY_VERSION=1.9
    - PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

    - PYTHON_VERSION=3.5 NUMPY_VERSION=1.9
    - PYTHON_VERSION=3.5 NUMPY_VERSION=1.11

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - wget ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio3370.tar.gz
    - tar -xzvf cfitsio3370.tar.gz
    - (cd cfitsio; ./configure --disable-shared --prefix=$HOME/cfitsio-static-install; make install -j 4)

install:
    - conda create --yes -n test python=$PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython
    - if [ $PYTHON_VERSION == 2.6 ]; then conda install --yes argparse; fi

script:
    - FITSIO_INSTALL_DIR=$HOME/fitsio-temp-install
    - export PYTHONPATH=$FITSIO_INSTALL_DIR/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH

    - python setup.py install --prefix=$FITSIO_INSTALL_DIR

    - pushd /tmp
    - SKIP_BZIP_TEST=true python -c "import fitsio; fitsio.test.test()"
    - popd
    - rm -rf $FITSIO_INSTALL_DIR

    - python setup.py clean -a 
    - python setup.py install --prefix=$FITSIO_INSTALL_DIR build_ext --use-system-fitsio --system-fitsio-includedir=$HOME/cfitsio-static-install/include --system-fitsio-libdir=$HOME/cfitsio-static-install/lib

    - pushd /tmp
    - SKIP_BZIP_TEST=true python -c "import fitsio; fitsio.test.test()"
    - popd
    - rm -rf $FITSIO_INSTALL_DIR

    - python setup.py clean -a
    - python setup.py build 
    - python setup.py clean -a
    - python setup.py build_ext

#notifications:
#  email: false
