/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__require
#define __PYX_HAVE__require


#ifndef __PYX_HAVE_API__require

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(int) require_python(void *);
__PYX_EXTERN_C DL_IMPORT(int) require_python_or_exit(void *);
__PYX_EXTERN_C DL_IMPORT(int) init_clips6_dummy(void *);

#endif /* !__PYX_HAVE_API__require */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initrequire(void);
#else
PyMODINIT_FUNC PyInit_require(void);
#endif

#endif /* !__PYX_HAVE__require */
