
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-25T07:04:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b02fbe8d852cf21570b84db66655faa327bfeef",
 "version": "2017.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
