# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_auto_20170320_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDetails',
            new_name='TaskDetail',
        ),
    ]
