# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_auto_20170320_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='parent_task_id',
        ),
    ]
