
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7a1b2373f87339bb4d66d08d3e19a498f136ae0b",
 "version": "0.0.0a37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
