
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-20T16:35:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6be5312b13c7544babe326c52413cc4787e2f4cb",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
