
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0c193715ba10c9a49b7d8e6e9868a25efea90798",
 "version": "0.0.0a25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
