# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.6.0.dev3'
VERSION = '0.6.0.dev3'
FULL_VERSION = '0.6.0.dev3'
GIT_REVISION = 'd545783afa4cbf68b19c05f97622272eb0ec5bb2'
GIT_VERSION = '0.6.0.dev3+d545783'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
