
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-21T10:50:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "602dce43d96946ccd942fd8262c97aae7a6b79bb",
 "version": "v1.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
