
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.11'
version_full = '6d949e784129f6e689e5c594863d08cc1a6d4e8d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

