
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8de2959e1aeef3d78ac5d4e67916b1245abc681f",
 "version": "2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
