
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1d76d5f78d6140f4424037485f2117c036138258",
 "version": "0.0.0a31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
