
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-23T19:16:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "333f980e240df96583ddddea7f3421a3e3acba28",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
