
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-23T11:31:44+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "b2d42aa37ff7e5d9e72d4e03942a461ba6d5abef",
 "version": "0.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
