
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-08T14:47:06+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "f822d0a2a17926102ff3e6e37f0be9ad044da773",
 "version": "0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
