
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-28T16:14:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb4739ed7e4629da09f92ca6fe104b99d8984af6",
 "version": "0.2.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
