---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "horizon"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "horizon"

- name: Copying over horizon.conf
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/horizon/horizon.conf"
  with_first_found:
    - "{{ node_custom_config }}/horizon/{{ inventory_hostname }}/horizon.conf"
    - "{{ node_custom_config }}/horizon/horizon.conf"
    - "horizon.conf.j2"

- name: Copying over local_settings
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/horizon/local_settings"
  with_first_found:
    - "{{ node_custom_config }}/horizon/{{ inventory_hostname }}/local_settings"
    - "{{ node_custom_config }}/horizon/local_settings"
    - "local_settings.j2"
