
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-19T18:28:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1ced940d4efb6f387a1416cc5ba2acd5bd3a0b7",
 "version": "1.0.0a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
