
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-21T19:58:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a0d1da45ba538f1e26b865a17394fd8f478bf03",
 "version": "2017.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
