
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-27T20:30:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc4c9b700f6e702ad8c3e9c9a7c50ed95f38e679",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
