
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7ce10c20615b58cf438738f9aae333674fb70df4",
 "version": "0.8.post34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
