
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a703c25a946aea5c91f9777cf05eba5ca5294cf9",
 "version": "1.0.0.post.dev311"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
