__version__ = "0.1.27"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'git@git.infinidat.com:host-opensource/infi.wmpio.git'
__git_head_hash__ = '3a8a5db8475f556c1bd59efe11536bf7cb02cd5a'
__git_head_subject__ = u'Finished Release v0.1.27'
__git_head_message__ = u'* develop:\n  HPT-2048 fixing previous commit'
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-03-01 20:36:34'
