
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2e441d61367c26cb22b9c17b21e2e0bbf1a74a86",
 "version": "2.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
