
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-26T12:40:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "de974194ffbd9dc360977944fc441b4de5d98043",
 "version": "2017.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
