
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-28T17:56:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f97a7789c2006b7cc1b6f1e7a472264c3c82121",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
