
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5b4ba9cbbe31a14a2ef8b6b6285ab70a1be4f639",
 "version": "0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
