
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "28fd616d56b901ec5ffb0b243d3d88b3182f3f28",
 "version": "0.0.0b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
