
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.9'
version_full = 'dc4ebbfb5d6057821fc0c57c512914ab249ac669'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

