all:
  - salt:
      admin_groups: None
      admin_users: None
      computer_name: None
      environment: False
      formula_termination_strings:
        - -master
        - -latest
      ou_path: None
      salt_states: Highstate
      s3_source: False
      user_formulas:
        #To add other formulas, make sure it is a url to a zipped file as follows:
        #- https://s3.amazonaws.com/salt-formulas/systemprep-formula-master.zip
        #- https://s3.amazonaws.com/salt-formulas/ash-linux-formula-master.zip
        #To "overwrite" submodule formulas, make sure name matches submodule names.

linux:
  - yum:
      repo_map:
        #SaltEL6:
        - dist:
            - redhat
            - centos
          el_version: 6
          url: https://s3.amazonaws.com/systemprep-repo/linux/saltstack/salt/yum.repos/salt-reposync-el6.repo
        - dist: amazon
          el_version: 6
          url: https://s3.amazonaws.com/systemprep-repo/linux/saltstack/salt/yum.repos/salt-reposync-amzn.repo
        #SaltEL7:
        - dist:
            - redhat
            - centos
          el_version: 7
          url: https://s3.amazonaws.com/systemprep-repo/linux/saltstack/salt/yum.repos/salt-reposync-el7.repo
  - salt:
      salt_debug_log: None
      content_source: https://s3.amazonaws.com/systemprep-content/linux/salt/salt-content.zip
      install_method: yum
      bootstrap_source: None
      git_repo: None
      salt_version: None

windows:
  - salt:
      salt_debug_log: None
      content_source: https://s3.amazonaws.com/systemprep-content/windows/salt/salt-content.zip
      installer_url: https://s3.amazonaws.com/systemprep-repo/windows/salt/Salt-Minion-2016.11.2-AMD64-Setup.exe
