
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "82c9a18de037518f80099396b5adbd1855c1fe92",
 "version": "0.9.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
