language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: osx
      language: generic
      env: PYTHON_VERSION=3

addons:
  apt:
    packages:
    - ttf-dejavu

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p ~/.fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O ~/.fonts/Ahem.ttf; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O /Library/Fonts/Ahem.ttf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget "http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-fonts-ttf-2.37.tar.bz2" -O /tmp/dejavu.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf /tmp/dejavu.tar.bz2 -C /tmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp /tmp/dejavu*/ttf/*.ttf /Library/Fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 cairo pango gdk-pixbuf libxml2 libxslt libffi; fi

install:
  - pip$PYTHON_VERSION install --upgrade setuptools pytest flake8
  - pip$PYTHON_VERSION install -e .

script:
  - python$PYTHON_VERSION -m pytest -s
  - python$PYTHON_VERSION -m flake8 weasyprint
