
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e5b5a38cfc746f41588f4d04b054d27069181e15",
 "version": "1.2.142"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
