
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d7f27d19e462ceaa073a7617af4e16c868604a84",
 "version": "2.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
