
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "43725f6dd596aab47150a2aa7da97cf03b96c573",
 "version": "0.0.0a34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
