
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-04T11:48:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "42bd5ac6a0b37fc0836fe8c50499c2854ecb7ffe",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
