
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-27T14:31:59-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "27fb8045f5f17a6fb7e478eec824af9651f91b5b",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
