
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-16T18:18:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8499d4e2c71045e5135e41aac905d9df9da4c64c",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
