
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-24T17:33:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4601df5af41f314e090ccbe80140d0bf11a48ef",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
