
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-17T12:53:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bab241d4662ddbfc51bc700495159ca5d6aed1d",
 "version": "0.1.62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
