
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-20T12:26:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9b1f361507d28fa1fdaa92362a4ce909b5228c3",
 "version": "0.0.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
