# coding: utf-8
# Generated by setup.py for PyCBC on 2017-02-20 14:10:29 +0000.

version = '1.6.6'
date = '2017-02-20 14:03:34 +0000'
release = True
last_release = '1.6.6'

git_hash = '6fa08f487105a825000dbdd82247c5125f83098d'
git_branch = 'None'
git_tag = 'v1.6.6'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Duncan Brown <duncan.brown@ligo.org>'
git_build_date = '2017-02-20 14:10:29 +0000'
git_verbose_msg = """Branch: None
Tag: v1.6.6
Id: 6fa08f487105a825000dbdd82247c5125f83098d
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2017-02-20 14:10:29 +0000
Repository status is CLEAN: All modifications committed"""