- name: wait for SSH
  hosts: all
  gather_facts: false
  roles:
    - check_ssh

- name: configure certificate authority, if necessary
  become: true
  hosts: certificate_authority
  gather_facts: false
  roles:
    - certificate_authority

- name: configure repositories
  become: true
  hosts: repositories
  roles:
    - repositories

- name: pre-configure jenkins
  become: true
  hosts: jenkins_master:jenkins_slave
  roles:
    - jenkins_common
    - beaker-client

- name: configure jenkins masters
  become: true
  hosts: jenkins_master
  roles:
    - jenkins_master
    - ntp

- name: configure jenkins slaves
  become: true
  hosts: jenkins_slave
  roles:
    - jenkins_slave
