
# This file is automatically generated from sisl setup.py
major   = 0
minor   = 8
micro   = 1
version = '.'.join(map(str,[0, 8, 1]))
release = True
# Git information
git_revision = '52da4445cc8686ae8c6436eebe7d0f6500c3921d'
git_revision_short = git_revision[:7]

if not release:
    version = version + '-' + git_revision
