title: Schema for Jenkins Git plugin configuration
type: object
additionalProperties: false

properties:

  user:
    type: object
    additionalProperties: false
    properties:
      email:
        description: |
          Email to use with git commits. Global setting to be used
          in call to "git config user.email".
        type: string

      name:
        description: |
          Name to use with git commits. Global setting to be used
          in call to "git config user.name".
        type: string

    required:
      - email
      - name
