language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
os:
  - linux
before-install:
  - pip install -r requirements.txt
script:
  - PYTHONPATH=. py.test
notifications:
  email:
    on_success: never
    on_failure: always
