# coding: utf-8
# Generated by setup.py for PyCBC on 2017-03-01 11:46:20 +0000.

version = '1.6.8'
date = '2017-03-01 11:21:09 +0000'
release = True
last_release = '1.6.8'

git_hash = '481883ea153da41d0e0e5398107c99aa8693c92b'
git_branch = 'None'
git_tag = 'v1.6.8'
git_author = 'Duncan Brown <dabrown@syr.edu>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Duncan Brown <duncan.brown@ligo.org>'
git_build_date = '2017-03-01 11:46:20 +0000'
git_verbose_msg = """Branch: None
Tag: v1.6.8
Id: 481883ea153da41d0e0e5398107c99aa8693c92b
Builder: Duncan Brown <duncan.brown@ligo.org>
Build date: 2017-03-01 11:46:20 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
