
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-28T13:02:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "055374b1a7634c422166e5b0509d1e6826c2b44a",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
