
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-09T15:43:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc6dfc01bdefeb457d1c374e8dc01080eac1f267",
 "version": "0.6.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
