
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "df0317f3a2a82878247ab545ea51b062325af1f8",
 "version": "1.2.147"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
