channels:
  - bioconda
  - r
dependencies:
  - pyyaml>=3.11
  - rpy2>=2.7.8
  - biopython>=1.68
  - star>=2.5.2b
  - rsem>=1.2.28
  - bamtools>=2.4.0
  - picard>=2.7.1
  - snakemake>=3.9.0
  - ucsc-gtftogenepred>=332
  - bioconductor-genomicfeatures>=1.26.0
  - bioconductor-rtracklayer>=1.34.1
