
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-18T18:07:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a40a36ea545b14d07f543d101060f1eb1e53155e",
 "version": "2017.3.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
