title: Schema for Global Jenkins configuration
type: object
additionalProperties: false
properties:
  admin_email:
    description: |
      Notification e-mails from Jenkins to project owners will be sent
      with this address in the from header.
    type: string

  agent_tcp_port:
    description: |
      TCP port for JNLP agents. You can specify the fixed port number so
      that you can configure your firewall accordingly. Defaults to
      random port number.
    type: integer

  location_url:
    description: |
      Address of the Jenkins installation, such as
      https://yourhost.yourdomain/jenkins/. This value is available as
      JENKINS_URL environment variable across builds and is used as a base for
      other environment variables, e.g. BUILD_URL.
    type: string

  markup_format:
    enum: ["plain-text", "raw-html", "unsafe"]
    description: |
      Markup formatter allows to use Raw HTML, Plain Text or unsafe markup
      for jobs, views descriptions.
    type: string

  num_of_executors:
    description: Number of executors for Master node.
    type: integer

  scm_checkout_retry_count:
    description: |
      If a build fails to checkout from the repository, Jenkins will retry
      the specified number of times before giving up.
    type: integer
