
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "637d049e64c09acd1124eb34b6ba1e0235ff65b7",
 "version": "0.0.0b6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
