
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.1'
version_full = 'da0eca7c15807108216d64b235c522ecacd975bc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

