# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='requestId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
