# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leprikon', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='journal_print_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leprikon.PrintSetup', verbose_name='journal print setup'),
        ),
        migrations.AddField(
            model_name='leprikonsite',
            name='journal_print_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leprikon.PrintSetup', verbose_name='journal print setup'),
        ),
        migrations.AddField(
            model_name='subjecttype',
            name='journal_print_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leprikon.PrintSetup', verbose_name='journal print setup'),
        ),
    ]
