
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c9787dc3c4f07d1314a6c7300685c4ded8e2ce76",
 "version": "0.0.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
