# Wire up travis
language: python
sudo: false

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=py2-cover
  - TOXENV=py3-cover

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - igor.stroh@rulim.de
