
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-18T18:04:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6d86a0a85ad75d173df61c9165879437bcaf754",
 "version": "2017.3.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
