
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.31.0'
version_full = '3bb1d9800d7771d8e0b6645e8f076f91bae54c2d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

