
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-28T18:58:24+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "df13c5a007574a2356b4c6858dd2f34c9f12f587",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
