
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-03T10:46:33+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "cb5cf0525941d2e073f327effa09b3b3d94d6eb8",
 "version": "1.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
