
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-17T21:03:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c568f339d2c7bc63289c8ba0bbdcf157f6cea73e",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
