# -*- coding: utf-8 -*-
# Copyright (c) 2015, pyretis Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for pyretis.

This file is generated by pyretis (``setup_version.py``)
"""
SHORT_VERSION = '0.2.1.dev1'
VERSION = '0.2.1.dev1'
FULL_VERSION = '0.2.1.dev1'
GIT_REVISION = '4a8dec976c77ea805ff7e0b8fe4914421d5ef03a'
GIT_VERSION = '0.2.1.dev1+4a8dec9'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
