---
- name: Starting collectd container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ collectd_image_full }}"
    name: "collectd"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/collectd/:{{ container_config_directory }}/:ro"
      - "{{node_config_directory }}/collectd/collectd.conf.d/:/etc/collectd/collectd.conf.d/"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
      - "/sys/:/sys/:ro"
      - "/dev/:/dev/:ro"
