# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryConfigSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=120)),
                ('celery_vhost', models.CharField(default='orch_default_vhost', max_length=120)),
                ('celery_default_queue', models.CharField(default='orch_default_queue', max_length=120)),
                ('celery_default_exchange', models.CharField(default='orch_default_queue_exchange', max_length=120)),
                ('celery_default_exchange_type', models.CharField(default='direct', max_length=120)),
                ('celery_default_routing_key', models.CharField(default='orch', max_length=120)),
                ('celery_imports', models.CharField(default='', max_length=120)),
                ('celery_result_backend', models.CharField(default='amqp', max_length=120)),
                ('celery_result_exchange', models.CharField(default='orch_default_result_exchange', max_length=120)),
                ('celery_result_exchange_type', models.CharField(default='orch_default_result_exchange_type', max_length=120)),
                ('updated_by', models.CharField(default='automation', max_length=256)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RabbitMQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_server', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
