title: Schema for Credentials Plugin
type: object
additionalProperties: false
properties:
  password:
    type: array
    additionalItems: false
    items:
      type: object
      properties:

        id:
          description: |
            An internal unique ID by which these credentials are identified from jobs and other
            configuration.
          type: string

        scope:
          description: |
            Global: Credentials discoverable by jobs and the Jenkins instance. Jobs can use those
            credentials for e.g. SCP build artifacts, Jenkins for launching slave on the machine.
            System: Credentials discoverable only by Jenkins instance for things like email auth,
            slave connection, etc, i.e. where the Jenkins instance itself is using the credential.
          enum: ['global', 'system']
          type: string

        username:
          description: Credential username.
          type: string

        password:
          description: Credential password for username or passphrase ssh username.
          type: string

        description:
          description: Credential description.
          type: string

      additionalProperties: false
      required:
      - scope
      - username
      - password

  ssh:
    type: array
    additionalItems: false
    items:
      type: object
      properties:

        id:
          description: |
            An internal unique ID by which these credentials are identified from jobs and other
            configuration.
          type: string

        scope:
          description: |
            Global: Credentials discoverable by jobs and the Jenkins instance. Jobs can use those
            credentials for e.g. SCP build artifacts, Jenkins for launching slave on the machine.
            System: Credentials discoverable only by Jenkins instance for things like email auth,
            slave connection, etc, i.e. where the Jenkins instance itself is using the credential.
          enum: ['global', 'system']
          type: string

        username:
          description: Credential username.
          type: string

        passphrase:
          description: Credential passphrase for ssh username.
          type: string

        description:
          description: Credential description.
          type: string

        private_key:
          description: |
            Private key can be entered directly here, can be specified path to a file on Jenkins master or
            just specify keyword: from-jenkins-ssh-dir to use private key from the Jenkins master ~/.ssh directory
          type: string

      additionalProperties: false
      required:
      - scope
      - username
      - private_key

  file:
    type: array
    additionalItems: false
    items:
      type: object
      properties:

        id:
          description: |
            An internal unique ID by which these credentials are identified from jobs and other
            configuration.
          type: string

        scope:
          description: |
            Global: Credentials discoverable by jobs and the Jenkins instance. Jobs can use those
            credentials for e.g. SCP build artifacts, Jenkins for launching slave on the machine.
            System: Credentials discoverable only by Jenkins instance for things like email auth,
            slave connection, etc, i.e. where the Jenkins instance itself is using the credential.
          enum: ['global', 'system']
          type: string

        file:
          description: Secret file path to load.
          type: string

        description:
          description: Credential description.
          type: string

      additionalProperties: false
      required:
      - scope
      - id
      - file


  kubernetes:
    type: array
    additionalItems: false
    description: |
      Read the OAuth bearer token from service account file provisioned by kubernetes
      Service Account Admission Controller when Jenkins itself is deployed inside a Pod.
    items:
      type: object
      properties:

        id:
          description: |
            An internal unique ID by which these credentials are identified from jobs and other
            configuration.
          type: string

        scope:
          description: |
            Global: Credentials discoverable by jobs and the Jenkins instance. Jobs can use those
            credentials for e.g. SCP build artifacts, Jenkins for launching slave on the machine.
            System: Credentials discoverable only by Jenkins instance for things like email auth,
            slave connection, etc, i.e. where the Jenkins instance itself is using the credential.
          enum: ['global', 'system']
          type: string

        description:
          description: Credential description.
          type: string

      additionalProperties: false
      required:
      - id
      - scope

  token:
    type: array
    additionalItems: false
    description: |
        A special case of password credentials. Credentials password will be filled with the API token
        of the user specified in 'username' field.
    items:
      type: object
      properties:

        id:
          description: |
            An internal unique ID by which these credentials are identified from jobs and other
            configuration.
          type: string

        scope:
          description: |
            Global: Credentials discoverable by jobs and the Jenkins instance. Jobs can use those
            credentials for e.g. SCP build artifacts, Jenkins for launching slave on the machine.
            System: Credentials discoverable only by Jenkins instance for things like email auth,
            slave connection, etc, i.e. where the Jenkins instance itself is using the credential.
          enum: ['global', 'system']
          type: string

        username:
          description: Username of an existing Jenkins user.
          type: string

        description:
          description: Credential description.
          type: string

      additionalProperties: false
      required:
      - id
      - scope
      - username

anyOf:
- required:
  - password
- required:
  - ssh
- required:
  - file
- required:
  - token
- required:
  - kubernetes
