# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0003_printpaper_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='verbose_name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='verbose_name_plural',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Pluralized category name'),
        ),
        migrations.AlterField(
            model_name='code',
            name='identifier',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Identifier'),
        ),
    ]
