# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0004_auto_20170222_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Added on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Added on'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='height',
            field=models.IntegerField(blank=True, default=297, help_text='(mm)', verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='width',
            field=models.IntegerField(blank=True, default=210, help_text='(mm)', verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='background',
            field=models.FileField(blank=True, default=None, null=True, upload_to='backgrounds/', verbose_name='Background'),
        ),
    ]
