# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0007_auto_20170223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printpaper',
            name='column_number',
            field=models.IntegerField(blank=True, default=1, help_text='(mm)', verbose_name='Number of columns'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='row_number',
            field=models.IntegerField(blank=True, default=1, help_text='(mm)', verbose_name='Number of rows'),
        ),
    ]
