# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0008_auto_20170223_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='printpaper',
            name='css',
            field=models.TextField(blank=True, default='', verbose_name='Template'),
        ),
    ]
