# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0009_printpaper_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='bar_code',
        ),
        migrations.RemoveField(
            model_name='code',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='printpaper',
            name='css',
        ),
        migrations.RemoveField(
            model_name='printpaper',
            name='template',
        ),
        migrations.AddField(
            model_name='code',
            name='long_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Long identifier'),
        ),
        migrations.AddField(
            model_name='code',
            name='short_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Short identifier'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='code_template',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Code template'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='css_template',
            field=models.TextField(blank=True, default='', verbose_name='CSS template'),
        ),
        migrations.AlterField(
            model_name='code',
            name='rfid_code',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='RFID identifier'),
        ),
    ]
