# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0010_auto_20170224_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='long_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Long identifier'),
        ),
        migrations.AddField(
            model_name='element',
            name='short_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Short identifier'),
        ),
        migrations.AlterField(
            model_name='code',
            name='short_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Short identifier'),
        ),
    ]
