# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0012_remove_element_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Object categories'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Registered object', 'verbose_name_plural': 'Registered objects'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'Object states'},
        ),
        migrations.AddField(
            model_name='code',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='code',
            name='serial',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=250, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='element',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='code_template',
            field=models.TextField(blank=True, default=None, help_text='Django template used for each label, with `paper` and `code` variables.', null=True, verbose_name='Label template'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='css_template',
            field=models.TextField(blank=True, default='', help_text='Django template that must render a CSS sheet, used in the rendered page, with `paper` variable.', verbose_name='CSS template'),
        ),
    ]
