resource_registry:
  OS::TripleO::Server: ../deployed-server/deployed-server.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: OS::Neutron::Port
  OS::TripleO::DeployedServer::Bootstrap: OS::Heat::None
