
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-06T10:51:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5949cf3203c0e4ddef0e029e08a96759006ec65",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
