
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-22T11:48:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "cca9cc7be93bd06d9ab79f8d7b7c4526a621bdbf",
 "version": "0.9.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
