
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-20T18:28:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d25af91ce54cc9e3389e55a36592b4673c0aed46",
 "version": "1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
