# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.6.0.dev2'
VERSION = '0.6.0.dev2'
FULL_VERSION = '0.6.0.dev2'
GIT_REVISION = '03a9b94ac66dffd7cdaa2a936eea1d54eb800237'
GIT_VERSION = '0.6.0.dev2+03a9b94'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
