
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c711ed4f11fc079f2d549cb68fa8f1c2ef87ac51",
 "version": "0.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
