# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniserver_app', '0001_initial'),
    ]

    operations = [
    ]
