language: python

sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

env:
    - DJANGO=Django==1.9.12
    - DJANGO=Django==1.10.5


before_install:
    - pip install codecov

install:
    - pip install --pre $DJANGO django-oscar==1.4
    - pip install -e .[test]

script:
    - py.test --cov=oscar_accounts

after_success:
    - codecov
