# This file was auto-generated by salt's setup on Wednesday, 22 February 2017 @ 21:02:04 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2016, 11, 3, 0, '', 0, 0, None)
