
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-20T16:17:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "19c468eebd2db7ca8d390195888e1020f9088686",
 "version": "1.0.0a11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
