# Autogenerated by Astropy's setup.py on 2017-03-05 20:00:44.282477
from __future__ import unicode_literals
import datetime

version = "1.0.12"
githash = "bc8bccced94407b42f843074a2482be03da62b74"


major = 1
minor = 0
bugfix = 12

release = True
timestamp = datetime.datetime(2017, 3, 5, 20, 0, 44, 282477)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
