# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.6.0.dev0'
VERSION = '0.6.0.dev0'
FULL_VERSION = '0.6.0.dev0'
GIT_REVISION = '75c5b118426af1296adda74cb3f70dc899048ab1'
GIT_VERSION = '0.6.0.dev0+75c5b11'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
