
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-17T01:06:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2601f9ab497bf632f5a025006d5dbd8b86357d8d",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
