
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bb000c2fa403eb1051556717f0d9aaa47bce84d7",
 "version": "0.0.0a33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
