
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9912daccd3dcc1f4165c42f2ce9788a0d7623586",
 "version": "0.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
