
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-13T12:18:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "12d100a56089f075a6ed9ffb9c2ba9bb610d7ae4",
 "version": "1.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
