
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4b0e41f92f7c0c081cfff0def3d50dcdccf6e9a4",
 "version": "1.0.0.post.dev320"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
