
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c37213b85312fb50c2b3658189e9d39e629b7c27",
 "version": "0.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
