
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cbc4ad3d7d322dc35ce798bf4553743c93802b48",
 "version": "0.0.0a30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
