
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-10T10:44:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "899ac47c1bb76150a2d12cd00ea4ce46bc4fa5b6",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
