
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-21T18:26:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8d8c53e36c0d652f02d92e12ab53e77057d4f0b",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
