#coding:utf-8
class A():
    def __init__(self):
        self.map = {"KATUNINSTALL":'kat被卸载',
                    "KATEXCEPTION":'kat异常',
                    "SETTINGEXCEPTION":'setting异常',
                    "PHONEEXCEPTION":'phone异常',
                    "SYSTEMUIEXCEPTION":'systemui异常',
                    "SDCARDONMOUNT":'sd卡处于挂载状态',
                    "SDCARDSTORAGE":'sd卡剩余空间',
                    "PHONESTORAGE":'手机系统剩余空间',
                    "AMEXCEPTION":'am运行异常',
                    "PMEXCEPTION":'pm运行异常',
                    "ACTIVITY_MANAGER_EXCEPTION":"Activity管理器异常",
                    "ADB_OFFLINE":"ADB掉线",
                    "SYSTEM_CRASH":"手机系统crash",
                    "LUA_NO_METHOD":"Lua方法调用异常",
                    "TOP_PROCESS_WRONG":"Top进程错误",
                    "LUA_FILE_LOST":"Lua脚本文件丢失",
                    "LIFE_CYCLE_SU":"SU通讯异常",
                    "LIFE_CYCLE_INI_ENV":"Kat初始化环境异常",
                    "LIFE_CYCLE_RUN_APP":"运行被测应用失败",
                    "LIFE_CYCLE_INSTRUMENTATION":"Instrumentation执行异常",
                    "LIFE_CYCLE_LUA":"Lua脚本程序未正常结束",
                    "LIFE_CYCLE_BRIDGE":"Bridge连接失败",
                    "KAT_DIRECTORY_BROKEN":"Kat系统目录异常",
                    "SDCARD_PERMISSION_DENIED":"sd卡权限不足",
                    "SU_COMMAND_LOST":"手机内部SU程序丢失",
                    "LIBLUAJAVA_NOT_FOUND":"LibLuaJava未找到",
                    "KAT_KILL_9":"Kat被强杀",
                    "ZYGOTE_304":"Zygote抛出304异常",
                    "SENDKEYEVENT_PERMISSION_DENIED":"发送KeyEvent权限不足",
                    "ZHOOK_FAIL":"ZHook失败",
                    "SYS_DEAD_BY_SERVICE":"系统多服务Dead",
                    "READ_ONLY_FILESYSTEM":"只读文件系统",
                    "KAT_VERSION":"Kat主版本错误",
                    "NOINTERCEPT":"无法拦截",
                    "INTER_KENEL":"Intel内核",
                    "FILESYSTEM":"文件系统问题",
                    "NOROOT":"无法Root",
                    "SDKLOWEST":"2.3SDK",
                    }
        self.known = {'6607': self.map["NOINTERCEPT"],
                'M4': self.map["NOINTERCEPT"],
                'LA6': self.map["NOINTERCEPT"],
                'WA1': self.map["NOINTERCEPT"],
                'X5L': self.map["NOINTERCEPT"],
                'A936': self.map["NOINTERCEPT"],
                'P70-t': self.map["NOINTERCEPT"],
                'Q2': self.map["NOINTERCEPT"],
                'M2U': self.map["NOINTERCEPT"],
                'K900': self.map["INTER_KENEL"],
                '8720L': self.map["FILESYSTEM"],
                '8089': self.map["FILESYSTEM"],
                'U819': self.map["FILESYSTEM"],
                '5910': self.map["FILESYSTEM"],
                'G6-C00': self.map["FILESYSTEM"],
                'X3S': self.map["NOROOT"],
                'R7005': self.map["NOROOT"],
                'T528t': self.map["NOROOT"],
                'T329t': self.map["NOROOT"],
                '8022': self.map["SDKLOWEST"],
                '8180': self.map["SDKLOWEST"],
                '8020+': self.map["SDKLOWEST"],
                '8070': self.map["SDKLOWEST"],
                'GN100': self.map["SDKLOWEST"],
                'C510e': self.map["SDKLOWEST"],
                'C8650': self.map["SDKLOWEST"],
                'C8650+': self.map["SDKLOWEST"],
                'T619+': self.map["SDKLOWEST"],
                'A218t': self.map["SDKLOWEST"],
                'A278t': self.map["SDKLOWEST"],
                'A288t': self.map["SDKLOWEST"],
                'A308t': self.map["SDKLOWEST"],
                'A318t': self.map["SDKLOWEST"],
                'A750': self.map["SDKLOWEST"],
                'P970': self.map["SDKLOWEST"],
                'XT615': self.map["SDKLOWEST"],
                'R801': self.map["SDKLOWEST"],
                'R807': self.map["SDKLOWEST"],
                'I9050': self.map["SDKLOWEST"],
                'I9070': self.map["SDKLOWEST"],
                'I9103': self.map["SDKLOWEST"],
                'N7000': self.map["SDKLOWEST"],
                'S5830i': self.map["SDKLOWEST"],
                'S6352': self.map["SDKLOWEST"],
                'I779': self.map["SDKLOWEST"],
                'i929': self.map["SDKLOWEST"],
                'W999': self.map["SDKLOWEST"],
                'LT18i': self.map["SDKLOWEST"],
                'MT11i': self.map["SDKLOWEST"],
                'MT15i': self.map["SDKLOWEST"],
                'R800i': self.map["SDKLOWEST"],
                'ST25i': self.map["SDKLOWEST"],
                'U790':self.map["SDKLOWEST"]
                }

a= A()
for key,value in a.known:
    print key,value

