heat_template_version: ocata

description: >
  AuditD configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  AuditdRules:
    description: Mapping of auditd rules
    type: json
    default: {}

outputs:
  role_data:
    description: Role data for the auditd service
    value:
      service_name: auditd
      config_settings:
        auditd::rules: {get_param: AuditdRules}
      step_config: |
        include ::tripleo::profile::base::auditd
