heat_template_version: ocata

description: >
  Openstack Mistral Engine service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  MistralBase:
    type: ./mistral-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Mistral Engine role.
    value:
      service_name: mistral_engine
      config_settings:
        get_attr: [MistralBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::mistral::engine
