
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-01T16:44:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7afc3b24b92dffb53834accff2ab66481be7cb87",
 "version": "0.1.0-rc.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
