
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-20T15:08:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec7e9cb2aa41adce7057e3e06a4e1e14e7e902f",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
