
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-28T09:40:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8159290dca5ccba2fe9e5b1f6b1053241712fbca",
 "version": "0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
