# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='extra_ratings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None, verbose_name='Extra ratings'),
        ),
    ]
