
# Autogenerated by Marvin's setup.py on 2017-02-16 11:26:09.265063
import datetime
from pkg_resources import get_distribution, DistributionNotFound
major = 2
minor = 1
bugfix = 0
release = True
timestamp = datetime.datetime(2017, 2, 16, 11, 26, 9, 265063)
version = '2.1.0'


def get_version():
    try:
        dist = get_distribution('sdss-marvin')
    except DistributionNotFound:
        return version
    else:
        return dist.version
    