
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-24T14:18:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bad58ae8973011e91c59ea7880291f8d2af1b71f",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
