# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.2.1.dev2'
VERSION = '0.2.1.dev2'
FULL_VERSION = '0.2.1.dev2'
GIT_REVISION = 'cd9160f7f613928dcc7ef16b9af71232801029f4'
GIT_VERSION = '0.2.1.dev2+cd9160f'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
