
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-28T15:29:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b29fd6c94aea2497aa7ef32f3504f6e9d21de00",
 "version": "0.10.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
