
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-21T06:05:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58333b8f48742f9b06b283edb01bb17899630067",
 "version": "2.0.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
