
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-01T11:01:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "415fc6e7955e197be7eb20e8a7eb8a52839b5514",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
