type: map
mapping:
  general:
    type: map
    allowempty: True
    mapping:
      lambda_timeout_time:
        type: int
        allowempty: True

  aws:
    type: map
    mapping:
      region:
        type: str
        pattern: ^[a-zA-Z0-9-]+$
        allowempty: True
      lambda_execution_role_name:
        type: str
        required: True
        pattern: ^[a-zA-Z0-9-_]+$
      subnet_ids:
        type: seq
        sequence:
          - type: str
      security_group_ids:
        type: seq
        sequence:
          - type: str

  lambdas:
    type: seq
    sequence:
      - type: map
        mapping:
          name:
            type: str
            required: True
            pattern: ^[a-zA-Z0-9_]+$
          description:
            type: str
            allowempty: True
          source:
            type: str
            required: True
          handler:
            type: str
            required: True
            pattern: ^[a-zA-Z0-9_]+$
          runtime:
            type: str
            required: True
            enum: ['nodejs', 'nodejs4.3', 'java8', 'python2.7']

  subscriptions:
    type: seq
    sequence:
      - type: map
        mapping:
          event:
            type: str
            required: True
            pattern: ^[a-zA-Z]+$
          subscribers:
            required: True
            type: seq
            sequence:
              - type: str

  workflows:
    type: seq
    sequence:
      - type: map
        mapping:
          id:
            type: str
            required: True
            pattern: ^[a-zA-Z_]+$
          flow:
            required: True
            type: seq
            sequence:
              - type: str
