# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printpaper',
            name='background',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Background'),
        ),
    ]
