# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0002_printpaper_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='printpaper',
            name='template',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Template'),
        ),
    ]
