# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0005_auto_20170223_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printpaper',
            name='height',
        ),
        migrations.RemoveField(
            model_name='printpaper',
            name='width',
        ),
        migrations.AddField(
            model_name='printpaper',
            name='label_height',
            field=models.IntegerField(blank=True, default=297, help_text='(mm)', verbose_name='Label height'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='label_width',
            field=models.IntegerField(blank=True, default=210, help_text='(mm)', verbose_name='Label width'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='paper_height',
            field=models.IntegerField(blank=True, default=297, help_text='(mm)', verbose_name='Paper height'),
        ),
        migrations.AddField(
            model_name='printpaper',
            name='paper_width',
            field=models.IntegerField(blank=True, default=210, help_text='(mm)', verbose_name='Paper width'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='column_space',
            field=models.IntegerField(blank=True, default=5, help_text='(mm)', verbose_name='Space between label columns'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='margin_left',
            field=models.IntegerField(blank=True, help_text='(mm)', verbose_name='Paper margin left'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='margin_top',
            field=models.IntegerField(blank=True, help_text='(mm)', verbose_name='Paper margin top'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='row_space',
            field=models.IntegerField(blank=True, default=5, help_text='(mm)', verbose_name='Space between label rows'),
        ),
    ]
