# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventicode', '0006_auto_20170223_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printpaper',
            name='column_number',
            field=models.FloatField(blank=True, default=1, help_text='(mm)', verbose_name='Number of columns'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='column_space',
            field=models.FloatField(blank=True, default=5, help_text='(mm)', verbose_name='Space between label columns'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='label_height',
            field=models.FloatField(blank=True, default=33.9, help_text='(mm)', verbose_name='Label height'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='label_width',
            field=models.FloatField(blank=True, default=63.5, help_text='(mm)', verbose_name='Label width'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='margin_left',
            field=models.FloatField(blank=True, help_text='(mm)', verbose_name='Paper margin left'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='margin_top',
            field=models.FloatField(blank=True, help_text='(mm)', verbose_name='Paper margin top'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='paper_height',
            field=models.FloatField(blank=True, default=297, help_text='(mm)', verbose_name='Paper height'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='paper_width',
            field=models.FloatField(blank=True, default=210, help_text='(mm)', verbose_name='Paper width'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='row_number',
            field=models.FloatField(blank=True, default=1, help_text='(mm)', verbose_name='Number of rows'),
        ),
        migrations.AlterField(
            model_name='printpaper',
            name='row_space',
            field=models.FloatField(blank=True, default=5, help_text='(mm)', verbose_name='Space between label rows'),
        ),
    ]
