
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-03-14T12:12:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "50b7213101469e86f8e543e10ff5c6f5d5d4f760",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
