
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b262a1c6ea2c9bfc97dcbf6658d3e08ac7b36cbf",
 "version": "1.2.157"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
